version: "3.8"

services:
  pb-go:
    image: 5keeve/pocketbook-go-sdk:6.3.0-b288-v1
    build:
      context: .
    entrypoint:
    - /go/bin/go
    command:
    - build
    volumes:
    - type: bind
      source: ./examples
      target: /app